version: '3.4'
services:
  apcupsdPrometheus:
    image: 'threevl/apcupsd-prometheus:0.1.0'
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
