{
 "title": "APCUPSD",
 "description": "APCUSD panel visualization as provided by https://github.com/3VLINC/apcupsd-prometheus",
 "tags": [ "apcupsd" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vector(1) and on() (apcupsd_info{status=\"ONLINE\"})) or (vector(0) and on() (apcupsd_info{status=\"ONBATT\"}))"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_battery_charge_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_load_percentage*apcupsd_nominal_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_time_left" }
   ]
  },
  {
   "title": "Current Time On Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_time_on_battery", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_battery_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_line_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Load Percentage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_load_percentage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "apcupsd_load_percentage*apcupsd_nominal_power",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Transfers to Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apcupsd_number_of_transfers_to_battery",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time on Battery",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "apcupsd_total_time_on_battery", "legendFormat": "__auto" }
   ]
  }
 ]
}